### ISSUE TITLE
Could you tell me if something like this was added in Adonis (lucid)?

### ISSUE THREAD

**Issue by ewertonrfd** [MZanggl/adonis-lucid-optional-queries#11]
Hi,
I saw that the code is from 2020
Could you tell me if something like this was added in Adonis (lucid) ?

Or as in the repository: adonis-lucid-when

I found the way you did it interesting, congratulations 👏

**Comment by MZanggl** [comment]
Best to check the docs as they are adding new things all the time. But you can always install this plugin yourself (see readme). If on Adonis v5, It's probably not hard to port it over.

**Comment by ewertonrfd** [comment]
Thank you @MZanggl 
Later in the documentation I saw that version 5 has IF in Adonis (in this case using model in lucid)
Then I'm using it, the reports are very easy to build 👏
I've done a lot of reports with "pure" PHP and it's really not easy, with IF's it's much easier to work

Att
